services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
      
  rag_engine:
    build:
      context: ./rag_engine
    container_name: rag_engine
    env_file: .env  
    depends_on:
      - qdrant
    volumes:
      - ./data:/data
      - ./rag_engine:/app
    command: sh -c "python clean.py && python ingest_qdrant.py"
  
  api:
    build:
      context: ./api
    container_name: api
    env_file: .env
    environment:
      - DEFAULT_SEARCH_LIMIT=${DEFAULT_SEARCH_LIMIT}
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    volumes:
      - ./api:/app
      - ./rag_engine:/app/rag_engine
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_SEARCH_LIMIT=${DEFAULT_SEARCH_LIMIT}
    depends_on:
      - api
