services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z

  rag_engine:
    build:
      context: ./rag_engine
    container_name: rag_engine
    env_file:
      - .env
    environment:
      - QDRANT_HOST=qdrant
    depends_on:
      - qdrant
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6333/" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./data:/app/data

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: cuisine_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - QDRANT_HOST=qdrant
    depends_on:
      - qdrant
    volumes:
      - ./data:/app/data
